### PR TITLE
Migrate to CodeRed Cloud

### PR DESCRIPTION
**Pull request by vsalvino**
Couple main changes in this request:
* Heavily removed dependencies that were not being used in the project, or are no longer needed. This was simply a side effect of me trying to get the project up and running for the first time. It looks like this came from a boilerplate because there was a lot in there not being used.
* Deleted heroku files to keep clutter out of the repo. There is no harm in keeping these around if so desired.
* Renamed production.py -> prod.py and changed the settings to support the configuration of CodeRed Cloud.
* Bumped one npm package version so that it would compile on my Windows dev machine 🤪 

This branch is running at: https://wagtailspace-us.codered.cloud/ and using a recent database dump from production, so try logging in and testing it out.

### CODE REVIEW

**Comment by vsalvino** [comment]
This appears to be working correctly, let me know if we are good to merge this in and want to coordinate a date/time to flip the switch?

cc @willbarton @Scotchester

**Comment by Scotchester** [comment]
Oh hey, right, this :)

We should merge this now, right, Vince?

**Comment by Scotchester** [comment]
:tada:

**Comment by vsalvino** [comment]
FYI if this repo is still connected to Heroku, it might break the Heroku build. @willbarton can safely decommission that now.

**Pull request merged**
